(setg dict.new         ListDict.new         )
(setg dict.is?         ListDict.is?         )
(setg dict.has?        ListDict.has?        )
(setg dict.get         ListDict.get         )
(setg dict.tryget      ListDict.tryget      )
(setg dict.keys        ListDict.keys        )
(setg dict.with-value  ListDict.with-value  )
(setg dict.with-values ListDict.with-values )
